apiVersion: apps/v1

kind: Deployment

metadata:

  name: cent

spec:

  selector:

    matchLabels:

      run: cent

  replicas: 1

  template:

    metadata:

      labels:

        run: cent

    spec:

      containers:

      - name: cent

        image: anandsadhu/dotnet-jenkins-slave

        ports:

        - containerPort: 5000
