apiVersion: apps/v1

kind: Deployment

metadata:

  name: chotu

spec:

  selector:

    matchLabels:

      run: chotu

  replicas: 1

  template:

    metadata:

      labels:

        run: chotu

    spec:

      containers:

      - name: chotu

        image: vincent53/chotu

        ports:

        - containerPort: 5000
