apiVersion: apps/v1

kind: Deployment

metadata:

  name: hasan

spec:

  selector:

    matchLabels:

      run: hasan

  replicas: 1

  template:

    metadata:

      labels:

        run: hasan

    spec:

      containers:

      - name: hasan

        image: vincent53/hasan

        ports:

        - containerPort: 5000
