apiVersion: apps/v1

kind: Deployment

metadata:

  name: cent
  namspace: Jenkins

spec:

  selector:

    matchLabels:

      run: cent

  replicas: 1

  template:

    metadata:

      labels:

        run: cent

    spec:

      containers:

      - name: cent

        image: vincent53/cent

        ports:

        - containerPort: 5000
