apiVersion: v1
kind: Service
metadata:
  name: chotu
  labels:
    run: chotu
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 80
    protocol: TCP
    name: http
 
  selector:
    run: chotu
