--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    run: myapp
  name: myapp
  namespace: dev
spec: 
  ports: 
    - 
      name: http
      port: 5000
      protocol: TCP
      targetPort: 85
  selector: 
    run: myapp
  type: NodePort
